// Copyright Kubotek Corporation, 1999-2014
// All Rights Reserved
#ifndef CKPTR_INC
#define CKPTR_INC

#ifndef _MSC_VER
#include "Enum.h"
#else
enum Result;
#endif

#include <GeMS/GemsFnd/Ptr.h>
#include <GeMS/GemsFnd/Gassert.h>
#include <GeMS/Utility/Compare.h>

// This file is provided as part of the KeyCreator SDK for reference only.
// The contents of this header file may change without notice.  These
// classes can not be used directly through the SDK.

#ifndef CADKEY_EXPORT
#ifdef _MSC_VER
#define CADKEY_EXPORT __declspec(dllimport)
#else
#define CADKEY_EXPORT __attribute__((visibility("default")))
#endif
#endif

class CADKEY_EXPORT CKPartRef;
class CADKEY_EXPORT CKEntity;
class CADKEY_EXPORT CKMatrix;
class CADKEY_EXPORT CKEntRef;

#ifndef TVIF_TEXT
typedef struct _TREEITEM *HTREEITEM;
#endif

#ifndef _WIN32
#define _PTRDIFF_T
#include <cstddef>
#endif

// @doc Internal

class CADKEY_EXPORT ck_ptr_base : public dyn_ptr_base
    {
    friend class CADKEY_EXPORT CKEntity;

public:
    // Constructing an empty pointer.
    ck_ptr_base(g_behaviors behave = WEAK_PTR, bool bCopyEntRefs = false);

    // Constructing an empty pointer.
    ck_ptr_base(std::nullptr_t, g_behaviors behave = WEAK_PTR,
                bool bCopyEntRefs = false);

    // Constructing a pointer to a real object.
    ck_ptr_base(CKEntity *v, g_behaviors behave = WEAK_PTR, bool bCopyEntRefs = false);

    // Constructing a pointer based on an entref pointer.
    ck_ptr_base(CKEntRef *p, g_behaviors behave = STRONG_PTR, bool bCopyEntRefs = false);

    // Constructing a pointer to an object based on another smart point.
    ck_ptr_base(const ptr_base &right, g_behaviors behave = WEAK_PTR, bool bCopyEntRefs = false);

    // Constructing a pointer based on an ck pointer, with behaviors.
    ck_ptr_base(const ck_ptr_base &rRight, g_behaviors behave, bool bCopyEntRefs = false);

    // Copy constructor.
    ck_ptr_base(const ck_ptr_base &rRight);

#ifdef _MSC_VER
    ck_ptr_base &operator=(nullptr_t v);
#else
    ck_ptr_base &operator=(int v);
#endif

    // Set the pointer equal to an object of type CKEntity.
    ck_ptr_base &operator=(CKEntity* v);

    // Set the pointer equal to an entref object.
    ck_ptr_base &operator=(CKEntRef *v);

    // Set the pointer equal to an object pointed to by a smart pointer.
    ck_ptr_base &operator=(const ptr_base &v);

    // Assign the value of another ck_ptr, of any type, to this pointer.
    // Type conversions are handled automatically.
    ck_ptr_base &operator=(const ck_ptr_base &rRight);

    // Compare this pointer to another ck pointer.
    bool operator==(const ck_ptr_base &right) const;

    // Compare this pointer to regular pointer.
    bool operator==(const CKEntity *right) const;

    // Compare this pointer to another ck pointer.
    bool operator!=(const ck_ptr_base &right) const;

    // Compare this pointer to regular pointer.
    bool operator!=(const CKEntity *right) const;

    GCompareResult compare(const ck_ptr_base &right) const;

protected:
    void Set(GAtom *p, CKEntity *pEntity);

    GAtom *CastToGAtom() const;

    void SetValue(CKEntity *pEntity);

    void SetWithCopy(const ck_ptr_base &rRight);

    void SetWithCopy(CKEntRef *pRef);

public:
    // Casting operator to get the entity pointer from this pointer.
    operator GAtom *() const { return(CastToGAtom()); }

    // Check to see if this is a direct (local) pointer, or an entref.
    bool IsLocal() const { return(nullptr == GetEntRef()); }

    // Get the current status of the pointer.
    Result GetStatus() const;

    // Get the entity to which this pointer refers, returning any result
    // codes generated by entrefs
    Result GetEntity(CKEntity *&rpEntity) const;

    // Return the entref to which this object refers, if any.
    CKEntRef *GetEntRef() const;

    // This checks for a nullptr _value without the downcast.  It's only
    // useful for checking for a nullptr pointer while streaming destantiated
    // pointers.
    bool value_is_null() const { return(_value == nullptr); }

protected:
    // These are the behaviors that the pointer has when it is in its weak
    // pointer state.  When it is in its strong pointer state, the
    // USE_COUNT_PTR behavior is added.
    mutable g_behaviors m_ucWeakBehaviors;

    // If true, then ent refs are always copied before assigned.
    mutable bool m_bCopyEntRefs;
    };

// @class The class for a pointer to an entity when that pointer can
// either be a direct entity pointer, or a pointer to a <c CKEntRef>.
// This pointer can not be used as a strong pointer to an entity.
//
// This class behaves as a weak pointer when pointing to an entity,
// and as a strong pointer when pointing to an EntRef.
//
// @base public | ck_ptr_base
template <class T> class ck_ptr : public ck_ptr_base
    {
public:
    // Constructing an empty pointer.
    ck_ptr(g_behaviors behave = WEAK_PTR, bool bCopyEntRefs = false) : 
        ck_ptr_base(behave, bCopyEntRefs) {}

    // Constructing an empty pointer.
    ck_ptr(std::nullptr_t, g_behaviors behave = WEAK_PTR,
           bool bCopyEntRefs = false) : 
        ck_ptr_base(nullptr, behave, bCopyEntRefs) {}

    // Constructing a pointer to a real object.
    ck_ptr(CKEntity *v, g_behaviors behave = WEAK_PTR, 
           bool bCopyEntRefs = false) : 
        ck_ptr_base(T::downcast(v), behave, bCopyEntRefs) {}

    // Constructing a pointer to an object based on another smart point.
    ck_ptr(const smart_ptr<T>& right, g_behaviors behave = WEAK_PTR, 
           bool bCopyEntRefs = false) : 
        ck_ptr_base(right, behave, bCopyEntRefs) {}

    // Constructing a pointer based on an entref pointer.
    ck_ptr(CKEntRef *p, g_behaviors behave = STRONG_PTR, 
           bool bCopyEntRefs = false) : 
        ck_ptr_base(p, behave, bCopyEntRefs) {}

    // Constructing a pointer based on an ck pointer, with behaviors.
    ck_ptr<T>(const ck_ptr_base &rRight, g_behaviors behave, 
              bool bCopyEntRefs = false) : 
        ck_ptr_base(rRight, behave, bCopyEntRefs) {}

    // Copy constructor.
    ck_ptr<T>(const ck_ptr_base &rRight) : ck_ptr_base(rRight) {}

#ifdef _MSC_VER
    ck_ptr<T> &operator=(nullptr_t)
        { ck_ptr_base::operator=(nullptr); return(*this); }
#else
    ck_ptr<T> &operator=(int)
        { ck_ptr_base::operator=(0); return(*this); }
#endif

    ck_ptr<T> &operator=(CKEntity *v)
        { ck_ptr_base::operator=(T::downcast(v)); return(*this); }
    ck_ptr<T> &operator=(CKEntRef *v)
        { ck_ptr_base::operator=(v); return(*this); }
    ck_ptr<T> &operator=(const ptr_base &v)
        { Set(v.cast(), T::downcast(v.cast())); return(*this); }
    ck_ptr<T> &operator=(const ck_ptr_base &v)
        { ck_ptr_base::operator=(v); return(*this); }

    bool operator==(const ck_ptr<T> &right) const
        { return(ck_ptr_base::operator==(right)); }
    bool operator!=(const ck_ptr<T> &right) const
        { return(ck_ptr_base::operator!=(right)); }
    bool operator==(const T *right) const { return(right == cast()); }
    bool operator!=(const T *right) const { return(right != cast()); }
    bool operator==(T *right) const { return(right == cast()); }
    bool operator!=(T *right) const { return(right != cast()); }

#ifdef _MSC_VER
    bool operator==(nullptr_t) const { return(nullptr == cast()); }
    bool operator!=(nullptr_t) const { return(nullptr != cast()); }
#else
    bool operator==(int v) const
        { ASSERT(0 == v); v; return(0 == cast()); }
    bool operator!=(int v) const
        { ASSERT(0 == v); v; return(0 != cast()); }
#endif

    GCompareResult compare(const ck_ptr<T> &right) const
        { return(ck_ptr_base::compare(right)); }

public:
    T *cast() const      { return(T::downcast(CastToGAtom())); }

    operator T *() const { return(cast()); }

    T *operator->() const
        {
        T *p = cast();
        ASSERT(p != nullptr);
        return(p);
        }

    bool operator!() const { return(nullptr == cast()); }

private:
    // Do not implement these functions!
    T &operator *();
    const T &operator *() const;
    };

#ifdef _MSC_VER
template <class T> inline bool operator==(nullptr_t, const ck_ptr<T> &right)
    { return(right.operator==(nullptr)); }

template <class T> inline bool operator!=(nullptr_t, const ck_ptr<T> &right)
    { return(right.operator!=(nullptr)); }
#else
template <class T> inline bool operator==(int, const ck_ptr<T> &right)
    { return(right.operator==(0)); }

template <class T> inline bool operator!=(int, const ck_ptr<T> &right)
    { return(right.operator!=(0)); }
#endif

#endif
