
#ifndef _GEMS_VERSION_H_
#define _GEMS_VERSION_H_

#define GEMS_MAJOR_VERSION 6
#define GEMS_MINOR_VERSION 1
#define GEMS_POINT_VERSION 6
#define GEMS_BUILD_VERSION 0
#define GEMS_BUILDNUM_STRING "6,1,6,0\0"

#define GEMS_BUILDNUM GEMS_MAJOR_VERSION,GEMS_MINOR_VERSION,GEMS_POINT_VERSION,GEMS_BUILD_VERSION

#endif
